# Generated by Django 4.2.7 on 2023-11-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobileNo', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('appointmentDate', models.DateField(blank=True, null=True, verbose_name='AppointmentDate Date(mm/dd/yyyy)')),
                ('area', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
