# Generated by Django 4.2.7 on 2023-11-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthPages', '0002_appointment_delete_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
