# Generated by Django 4.2.7 on 2023-11-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthPages', '0003_appointment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
